Models/ErrorViewModel.cs
namespace Test_task.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/InputController.cs
using Microsoft.AspNetCore.Mvc;

namespace Test_task.Controllers
{
    public class InputController : Controller
    {
        public IActionResult Input() { return View(); }

        public IActionResult InputNameOfCategory(string nameOfCategory)
        {
            return RedirectToAction("Output", "Output", new { nameOfCategory });
        }
    }
}

Controllers/OutputController.cs
using Microsoft.AspNetCore.Mvc;
using Test_task.Services;

namespace Test_task.Controllers
{
    public class OutputController : Controller
    {
        private readonly GetService _getService;

        public OutputController(GetService getService)
        {
            _getService = getService;
        }

        public async Task<IActionResult> Output(string nameOfCategory)
        {
            var outputObjects = await _getService.GetJoinedProductsAndCategories(nameOfCategory);

            return View(outputObjects);
        }
    }
}

Views/Input/Input.cshtml
<div>
    <p>Автоматически добавлены категории Еда, Напитки , Автомасла , Крупы (пустая)</p>
</div>
<form asp-action="InputNameOfCategory">
    <label>Введите название категории</label><br /><br />
    <input type="text" name="nameOfCategory" /><br /><br />
    <input type="submit" value="Показать" />
</form>

Views/Output/Output.cshtml
@using Test_task.Data;
@model List<OutputObject>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Static Template</title>
</head>
<body>
    <div>
        <table class="table" width="100">
            <thead>
                <tr>
                    <th>Наименование категори</th>
                    <th>Наименование товара</th>
                    <th>Цена товара</th>
                    <th>Описание товара</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var data in Model)
                {
                    <tr>
                        <td>@data.NameOfCategory</td>
                        <td>@data.NameOfProduct</td>
                        <td>@data.Price</td>
                        <td>@data.Description</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test_task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test_task.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Input" asp-action="Input">Test_task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>